version: 2

project_name: hardpointd

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/hardpointlabs/agent/config.Version={{ .Version }}
      - -X github.com/hardpointlabs/agent/config.Commit={{ .Commit }}

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

nfpms:
  - id: default
    package_name: hardpointd
    vendor: Hardpoint
    homepage: https://hardpoint.dev
    maintainer: Support <support@hardpoint.dev>
    description: Hardpoint agent
    license: Apache 2.0
    formats:
      - deb
    section: admin
    priority: optional
    bindir: /usr/bin

kos:
  - id: default
    repositories:
      - ghcr.io/hardpointlabs/agent
    bare: true
    tags:
      - "{{.Tag}}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: spdx
    sbom_directory: "out/sbom"

sboms:
  - id: default
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]
    artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: hardpointd
    commit_author:
      name: Chris Mowforth
      email: chris.mowforth@hardpoint.dev
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Hardpoint agent"
    hooks:
      post:
        install: |
          bin.install "hardpointd"
          system "#{bin}/hardpointd --version"
    repository:
      owner: hardpointlabs
      name: homebrew-agent
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
