version: 2

project_name: hardpointd

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/hardpointlabs/agent/config.Version={{ .Version }}
      - -X github.com/hardpointlabs/agent/config.Commit={{ .Commit }}

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

nfpms:
  - id: default
    package_name: hardpointd
    vendor: Hardpoint
    homepage: https://hardpoint.dev
    maintainer: Support <support@hardpoint.dev>
    description: Hardpoint agent
    license: Apache 2.0
    formats:
      - deb
    section: admin
    priority: optional
    bindir: /usr/bin
    contents:
      - src: packaging/debconf-templates
        dst: /usr/share/debconf/templates/hardpointd
        file_info:
          mode: 0644
      - src: packaging/hardpointd.service
        dst: /lib/systemd/system/hardpointd.service
        file_info:
          mode: 0644
    scripts:
      postinstall: packaging/postinst
      preremove: packaging/prerm
      postremove: packaging/postrm
    deb:
      scripts:
        config: packaging/config

# Sign all package artifacts (deb files)
signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_KEY_ID }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    signature: "${artifact}.sig"
    artifacts: package
    ids:
      - default

kos:
  - id: default
    repositories:
      - ghcr.io/hardpointlabs/agent
    bare: true
    annotations:
      org.opencontainers.image.source: "https://github.com/hardpointlabs/agent"
      org.opencontainers.image.licenses: "BUSL-1.1"
      org.opencontainers.image.description: "Hardpoint agent"
    tags:
      - "{{.Tag}}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: spdx
    sbom_directory: "out/sbom"

sboms:
  - id: default
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]
    artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: hardpointd
    commit_author:
      name: Chris Mowforth
      email: chris.mowforth@hardpoint.dev
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Hardpoint agent"
    hooks:
      post:
        install: |
          bin.install "hardpointd"
          system "#{bin}/hardpointd --version"
    repository:
      owner: hardpointlabs
      name: homebrew-agent
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"